version: '3.9'
services:
  url:
    image: urln
    container_name: 'codyp.us'
    ports:
      - '94:80'
      - '447:443'
    volumes:
      - './Database:/app/Database'
      - './cert/:/app/cert'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+;https://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=<my-cert-password>
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./cert/domain.pfx
    entrypoint:
      [ "dotnet", "Url.Api.dll" ]  
